'use client'
import {useEffect,useMemo,useState} from 'react'
import {stages,allLessons} from '../data/roadmap'
export default function Home(){
 const [done,setDone]=useState<string[]>([]); const [q,setQ]=useState(''); const [active,setActive]=useState('all'); const [open,setOpen]=useState<string|null>(null)
 useEffect(()=>{try{setDone(JSON.parse(localStorage.getItem('naol-ve-v2')||'[]'))}catch{}} ,[])
 const toggle=(id:string)=>{const n=done.includes(id)?done.filter(x=>x!==id):[...done,id];setDone(n);localStorage.setItem('naol-ve-v2',JSON.stringify(n))}
 const filtered=useMemo(()=>allLessons.filter(l=>(active==='all'||l.stageId===active)&&(!q||`${l.title} ${l.tag} ${l.why}`.toLowerCase().includes(q.toLowerCase()))),[q,active])
 const pct=Math.round(done.length/allLessons.length*100)
 return <main><header><div className="brand">NAOL <span>/// EDITING ROADMAP</span></div><nav><a href="#roadmap">Roadmap</a><a href="#resources">Resources</a><a href="#projects">Projects</a><a href="#money">Money</a></nav></header>
 <section className="hero"><div><p className="eyebrow">VIDEO EDITING · V2</p><h1>Learn the editor’s brain.<br/><em>Build real work.</em></h1><p className="lead">A directed path from editing fundamentals to Kdenlive fluency, portfolio projects, professional workflow, and your first editing offer.</p><div className="actions"><a className="btn primary" href="#roadmap">Start roadmap</a><button className="btn" onClick={()=>{localStorage.removeItem('naol-ve-v2');setDone([])}}>Reset progress</button></div></div><div className="progress"><strong>{pct}%</strong><span>{done.length} / {allLessons.length} lessons</span><div className="bar"><i style={{width:`${pct}%`}}/></div><small>Learn → Practice → Build → Prove</small></div></section>
 <section className="stats"><div><b>{stages.length}</b><span>paths</span></div><div><b>{allLessons.length}</b><span>directed lessons</span></div><div><b>6</b><span>portfolio projects</span></div><div><b>100%</b><span>resource-linked</span></div></section>
 <section id="roadmap" className="workspace"><aside><h3>Roadmap</h3><button className={active==='all'?'sel':''} onClick={()=>setActive('all')}>All lessons</button>{stages.map(s=><button key={s.id} className={active===s.id?'sel':''} onClick={()=>setActive(s.id)}>{s.title}<small>{s.lessons.filter(l=>done.includes(l.id)).length}/{s.lessons.length}</small></button>)}<div className="side-note"><b>Your rule</b><p>Don’t just watch. Every lesson ends with a practice or build task.</p></div></aside><div className="content"><div className="toolbar"><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search lessons, skills, projects..."/><span>{filtered.length} results</span></div>{stages.map(stage=>{const items=filtered.filter(l=>l.stageId===stage.id);if(!items.length)return null;return <section className="stage" key={stage.id} id={stage.id}><div className="stagehead"><div><p className="eyebrow">STAGE</p><h2>{stage.title}</h2><p>{stage.subtitle}</p></div><span>{stage.lessons.filter(l=>done.includes(l.id)).length}/{stage.lessons.length}</span></div>{items.map((l,i)=><article className={'lesson '+(done.includes(l.id)?'complete':'')} key={l.id}><div className="num">{String(i+1).padStart(2,'0')}</div><div className="lessonmain"><div className="lessonline"><span className="tag">{l.tag}</span><h3>{l.title}</h3></div><p>{l.why}</p><div className="details"><div><b>LEARN</b><span>{l.learn}</span></div><div><b>PRACTICE</b><span>{l.practice}</span></div><div><b>BUILD</b><span>{l.build}</span></div><div><b>DONE WHEN</b><span>{l.criteria}</span></div></div><button className="resourceToggle" onClick={()=>setOpen(open===l.id?null:l.id)}>{open===l.id?'Hide':'Show'} learning resources ({l.resources.length})</button>{open===l.id&&<div className="resources">{l.resources.map(r=><a key={r.url} href={r.url} target="_blank" rel="noreferrer"><span>{r.type}</span><strong>{r.title}</strong><small>{r.free?'FREE · Open resource':''}</small></a>)}</div>}</div><button className="check" onClick={()=>toggle(l.id)} aria-label="complete">{done.includes(l.id)?'✓':'○'}</button></article>)}</section>})}</div></section>
 <section id="resources" className="feature"><p className="eyebrow">RESOURCE SYSTEM</p><h2>Every skill has a place to learn it.</h2><p>Kdenlive lessons point to the official manual, Quick Start, tutorials, editing documentation, color/audio material, export guidance, and proxy workflow. The official manual covers editing, effects, transitions, titles, color correction, audio, and export.</p><div className="resourceGrid"><a href="https://docs.kdenlive.org/en/getting_started/quickstart.html" target="_blank">Kdenlive Quick Start →</a><a href="https://docs.kdenlive.org/en/getting_started/tutorials.html" target="_blank">Kdenlive Tutorials →</a><a href="https://docs.kdenlive.org/en/cutting_and_assembling/editing.html" target="_blank">Timeline & Editing →</a><a href="https://docs.kdenlive.org/en/project_and_asset_management/project_settings/proxy_settings.html" target="_blank">Proxy Workflow →</a></div></section>
 <section id="projects" className="feature"><p className="eyebrow">PORTFOLIO</p><h2>Build proof, not certificates.</h2><p>Six projects move from cinematic editing to YouTube, tech tutorials, short-form, product promo, and documentary work.</p></section><section id="money" className="feature"><p className="eyebrow">MONEY PATH</p><h2>Turn the skill into an offer.</h2><p>Choose a niche, build samples, find prospects, define scope, and create a repeatable workflow.</p></section>
 <footer>NAOL / VIDEO EDITING ROADMAP · V2 · Learn. Practice. Build. Deliver.</footer></main>
}
